version: '3.9'

services:

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - student-attendance-system-api-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - spring-app
    networks:
      - student-attendance-system-api-network

networks:
  student-attendance-system-api-network:
    driver: bridge