version: '3.9'

services:
  postgres:
    image: postgres:14.9-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mytestuser
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=student_attendance_system_db
    networks:
      - student-attendance-system-api-network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - student-attendance-system-api-network

networks:
  student-attendance-system-api-network:
    driver: bridge
